language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:  coverage run --source cookiecutter tests.py test


after_success:
    coveralls

notifications:
  email:
  - lennymanyeki@gmail.com